### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by yuninn** [GreatGameDota/context-rcnn-pytorch#1]
Hello, I am very interested in this project. Can you provide documentation for this pytorch project, such as requirement.txt. Looking forward to your reply!

**Comment by GreatGameDota** [comment]
I added a requirements.txt file so you should be able to run the code now. If you want me to add anything else let me know!

**Comment by yuninn** [comment]
Thank you very much!I will try it.



---Original---
From: ***@***.***&gt;
Date: Wed, Sep 29, 2021 02:47 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [GreatGameDota/context-rcnn-pytorch] How to run this project? (#1)




 
I added a requirements.txt file so you should be able to run the code now. If you want me to add anything else let me know!
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
