### ISSUE TITLE
How to train CONTEXT R-CNN？

### ISSUE THREAD

**Issue by yuninn** [GreatGameDota/context-rcnn-pytorch#2]
Excuse me, I want to know how I can use my own data to train context r-cnn, I did not find train.py. What should the data format be? Is it the same as VOC2007?

**Comment by GreatGameDota** [comment]
The bbox format is Pascal VOC (xmin, ymin, xmax, ymax). The model can be plugged in to a normal F-RCNN training pipeline and to use the attention you just need to either include context images in the training or embed features of those images. (Unless you only use self-attention then you don't need any extra input)

**Comment by yuninn** [comment]
> The bbox format is Pascal VOC (xmin, ymin, xmax, ymax). The model can be plugged in to a normal F-RCNN training pipeline and to use the attention you just need to either include context images in the training or embed features of those images. (Unless you only use self-attention then you don't need any extra input)

Thank you for your enthusiastic reply, do you have a complete example to embed this model into f-rcnn, rcnn input single frame and context-input multiple frames I am a little puzzled how to embed this model.

**Comment by GreatGameDota** [comment]
Sadly I do not have a fully implemented training example with the model because this project is very much unfinished. Only thing I included was the test file in tests/ which shows example input and tests the output.

**Comment by yuninn** [comment]
> Sadly I do not have a fully implemented training example with the model because this project is very much unfinished. Only thing I included was the test file in tests/ which shows example input and tests the output.

Thanks for your help, I will try it by myself.
